services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "7777:443"
    depends_on:
      - next
    networks:
      - app-network


networks:
  app-network:
    driver: bridge