services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    # ports:
    #   - "3000:3000" 
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:1.27.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx:/etc/nginx
      - ./cert:/cert
    ports:
      - "443:443"
    depends_on:
      - next
    networks:
      - app-network


networks:
  app-network:
    driver: bridge