package com.danielfreitassc.backend.utils;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

public class ForbiddenWordsFilterWindows {
    private static final Set<String> FORBIDDEN_WORDS = new HashSet<>(Arrays.asList(
        "ALLUSERSPROFILE", "APPDATA", "COMMONPROGRAMFILES", "COMMONPROGRAMFILES(X86)", 
        "COMMONPROGRAMW6432", "COMPUTERNAME", "COMSPEC", "DRIVERDATA", "HOMEDRIVE", 
        "HOMEPATH", "LOCALAPPDATA", "LOGONSERVER", "NUMBER_OF_PROCESSORS", "OS", 
        "PATHEXT", "PROCESSOR_ARCHITECTURE", "PROCESSOR_IDENTIFIER", "PROCESSOR_LEVEL", 
        "PROCESSOR_REVISION", "PROGRAMDATA", "PROGRAMFILES", "PROGRAMFILES(X86)", 
        "PROGRAMW6432", "PUBLIC", "SESSIONNAME", "SYSTEMDRIVE", "SYSTEMROOT", 
        "TEMP", "TMP", "USERDOMAIN", "USERDOMAIN_ROAMINGPROFILE", "USERNAME", 
        "USERPROFILE", "WINDIR", "ALLUSERSAPPDATA", "CSIDL_COMMON_ADMINTOOLS",
        "CSIDL_COMMON_ALTSTARTUP", "CSIDL_COMMON_APPDATA", "CSIDL_COMMON_DESKTOPDIRECTORY",
        "CSIDL_COMMON_DOCUMENTS", "CSIDL_COMMON_FAVORITES", "CSIDL_COMMON_MUSIC",
        "CSIDL_COMMON_PICTURES", "CSIDL_COMMON_PROGRAMS", "CSIDL_COMMON_STARTMENU",
        "CSIDL_COMMON_STARTUP", "CSIDL_COMMON_TEMPLATES", "CSIDL_COMMON_VIDEO",
        "CSIDL_DEFAULT_APPDATA", "CSIDL_DEFAULT_LOCAL_APPDATA", "CSIDL_DEFAULT_COOKIES",
        "CSIDL_DEFAULT_CONTACTS", "CSIDL_DEFAULT_DESKTOP", "CSIDL_DEFAULT_DOWNLOADS",
        "CSIDL_DEFAULT_FAVORITES", "CSIDL_DEFAULT_HISTORY", "CSIDL_DEFAULT_INTERNET_CACHE",
        "CSIDL_DEFAULT_PERSONAL", "CSIDL_DEFAULT_MYDOCUMENTS", "CSIDL_DEFAULT_MYPICTURES",
        "CSIDL_DEFAULT_MYMUSIC", "CSIDL_DEFAULT_MYVIDEO", "CSIDL_DEFAULT_RECENT",
        "CSIDL_DEFAULT_SENDTO", "CSIDL_DEFAULT_STARTMENU", "CSIDL_DEFAULT_PROGRAMS",
        "CSIDL_DEFAULT_STARTUP", "CSIDL_DEFAULT_TEMPLATES", "CSIDL_DEFAULT_QUICKLAUNCH",
        "CSIDL_FONTS", "CSIDL_PROGRAM_FILESX86", "CSIDL_PROGRAM_FILES_COMMONX86",
        "CSIDL_PROGRAM_FILES", "CSIDL_PROGRAM_FILES_COMMON", "CSIDL_RESOURCES",
        "CSIDL_SYSTEM", "CSIDL_WINDOWS", "DEFAULTUSERPROFILE", "PROFILESFOLDER",
        "PROGRAMFILES", "PROGRAMFILES(X86)", "SISTEMA", "SYSTEM16", "SYSTEM32",
        "SYSTEMDRIVE", "SYSTEMPROFILE", "SYSTEMROOT", "WINDIR", "CSIDL_ADMINTOOLS",
        "CSIDL_ALTSTARTUP", "CSIDL_APPDATA", "CSIDL_BITBUCKET", "CSIDL_CDBURN_AREA",
        "CSIDL_CONNECTIONS", "CSIDL_CONTACTS", "CSIDL_CONTROLS", "CSIDL_COOKIES",
        "CSIDL_DESKTOP", "CSIDL_DESKTOPDIRECTORY", "CSIDL_DRIVES", "CSIDL_FAVORITES",
        "CSIDL_HISTORY", "CSIDL_INTERNET", "CSIDL_INTERNET_CACHE", "CSIDL_LOCAL_APPDATA",
        "CSIDL_MYDOCUMENTS", "CSIDL_MYMUSIC", "CSIDL_MYPICTURES", "CSIDL_MYVIDEO",
        "CSIDL_NETHOOD", "CSIDL_NETWORK", "CSIDL_PERSONAL", "CSIDL_PLAYLISTS",
        "CSIDL_PRINTERS", "CSIDL_PRINTHOOD", "CSIDL_PROFILE", "CSIDL_PROGRAMS",
        "CSIDL_RECENT", "CSIDL_SENDTO", "CSIDL_STARTMENU", "CSIDL_STARTUP",
        "CSIDL_TEMPLATES", "HOMEPATH", "TEMP", "TMP", "USERPROFILE", "USERSID"
    ).stream().map(String::toUpperCase).collect(Collectors.toSet()));

    public static boolean containsForbiddenWords(String value) {
        return FORBIDDEN_WORDS.contains(value.toUpperCase());
    }
}
