spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/mydatabase;AUTO_SERVER=TRUE
    username: ${ENV_VAULT_USER:admin}
    password: ${ENV_VAULT_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JTW_VAULT_SECRET:my-secret-key}

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: sua-senha-segura-123
    key-store-type: PKCS12
    key-alias: springboot-server
  port: 7778